language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - python -m coverage run -m pytest -s -v tests
  - python -m coverage xml -o cobertura.xml
  - 'bash <(curl -Ls https://coverage.codacy.com/get.sh) report'

